hedley: fix v13 build with old AppleClang (Travis "xcode7.3" and "xcode8")
Compilation fails in "xcode7.3" (clang-703.0.31) and "xcode8" (clang-800.0.38)
Compilation succeeds in "xcode8.3" (clang-802.0.42) and later

Code sample:
  HEDLEY_WARN_UNUSED_RESULT
  HEDLEY_DEPRECATED(1.0.0)
  int func()
  {
      return 123;
  }

Compile error:
  /Users/travis/build/mnfdev/test-hedley/main.cpp:4:1: error: an attribute list cannot appear here
  HEDLEY_DEPRECATED(1.0.0)
  ^~~~~~~~~~~~~~~~~~~~~~~~
  /Users/travis/build/mnfdev/test-hedley/hedley.h:945:81: note: expanded from macro 'HEDLEY_DEPRECATED'
  #  define HEDLEY_DEPRECATED(since) HEDLEY_DIAGNOSTIC_DISABLE_CPP98_COMPAT_WRAP_([[deprecated("Since " #since)]])
                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~